
$out = [System.Collections.Generic.List[string]]::new()
function W($s){ $out.Add($s) }

W '<!DOCTYPE html>'
W '<html lang="id" data-theme="light">'
W '<head>'
W '<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">'
W '<title>Audit Finansial Terpadu - Fahmi Fahrezy</title>'
W '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet">'
W '<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>'
W '<script src="assets/vendor/pdfjs/pdf.min.js"></script>'
W '<script src="assets/js/pdf_bundle.js"></script>'
W '<script src="assets/js/xbet_data.js"></script>'
W '<style>'
W '*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}'
W ':root{--sw:240px;--hh:60px;--f:"Inter",-apple-system,sans-serif;--m:"JetBrains Mono",monospace;--tr:all .18s ease}'
W '[data-theme=light]{--bg:#f0f2f5;--s:#fff;--s2:#f7f8fa;--s3:#eef0f4;--b:#e3e7ef;--b2:#d4d9e5;--t1:#0d1117;--t2:#3d4452;--t3:#6b7280;--t4:#9ca3af;--ac:#2563eb;--ag:#eff6ff;--ab:#bfdbfe;--gr:#16a34a;--gs:#f0fdf4;--rd:#dc2626;--rs:#fef2f2;--am:#d97706;--as:#fffbeb;--pu:#7c3aed;--ps:#f5f3ff;--sh:0 1px 3px rgba(0,0,0,.06);--sbl:#fff;--sbbd:#e3e7ef;--sbac:#f0f5ff;--sbat:#2563eb;--sbh:#f7f8fa}'
W '[data-theme=dark]{--bg:#0a0c10;--s:#111318;--s2:#161a22;--s3:#1c2130;--b:#252b38;--b2:#1e2534;--t1:#f1f5f9;--t2:#94a3b8;--t3:#64748b;--t4:#475569;--ac:#60a5fa;--ag:rgba(96,165,250,.1);--ab:rgba(96,165,250,.2);--gr:#4ade80;--gs:rgba(74,222,128,.08);--rd:#f87171;--rs:rgba(248,113,113,.1);--am:#fbbf24;--as:rgba(251,191,36,.1);--pu:#a78bfa;--ps:rgba(167,139,250,.1);--sh:0 1px 3px rgba(0,0,0,.4);--sbl:#0e1118;--sbbd:#1e2534;--sbac:rgba(96,165,250,.1);--sbat:#60a5fa;--sbh:rgba(255,255,255,.03)}'
W 'html,body{height:100%;overflow:hidden}'
W 'body{font-family:var(--f);background:var(--bg);color:var(--t1);font-size:13px;line-height:1.5;-webkit-font-smoothing:antialiased;display:flex;transition:var(--tr)}'
W '.mono{font-family:var(--m)}'
W '.sidebar{width:var(--sw);min-width:var(--sw);height:100vh;background:var(--sbl);border-right:1px solid var(--sbbd);display:flex;flex-direction:column;position:fixed;left:0;top:0;z-index:50;overflow-y:auto;transition:var(--tr)}'
W '.sb-top{padding:16px 16px 10px;display:flex;align-items:center;gap:8px;border-bottom:1px solid var(--sbbd)}'
W '.sb-ico{width:30px;height:30px;background:var(--ac);border-radius:7px;display:flex;align-items:center;justify-content:center;color:#fff;flex-shrink:0}'
W '.sb-name{font-size:14px;font-weight:800;color:var(--t1);letter-spacing:-.3px}'
W '.sb-badge{font-size:10px;font-weight:700;background:var(--ag);color:var(--ac);border:1px solid var(--ab);padding:1px 6px;border-radius:9999px;margin-left:auto}'
W '.sb-user{padding:12px 14px 8px;display:flex;align-items:center;gap:10px}'
W '.sb-av{width:36px;height:36px;background:linear-gradient(135deg,#1e40af,#3b82f6);border-radius:50%;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:800;font-size:12px;flex-shrink:0}'
W '.sb-un{font-size:13px;font-weight:700;color:var(--t1)}.sb-us{font-size:11px;color:var(--t3);margin-top:1px}'
W '.sb-nav{padding:6px 8px;flex:1}'
W '.sb-lbl{font-size:10px;font-weight:700;color:var(--t4);text-transform:uppercase;letter-spacing:.6px;padding:10px 8px 5px}'
W '.nb{display:flex;align-items:center;gap:8px;width:100%;padding:7px 10px;border-radius:7px;border:none;background:transparent;color:var(--t2);font-size:12.5px;font-weight:500;cursor:pointer;font-family:var(--f);text-align:left;transition:var(--tr);margin-bottom:1px}'
W '.nb:hover{background:var(--sbh);color:var(--t1)}.nb.act{background:var(--sbac);color:var(--sbat);font-weight:600}'
W '.nb svg{flex-shrink:0;opacity:.7}.nb.act svg{opacity:1}'
W '.nb-ct{margin-left:auto;font-size:10px;font-weight:700;padding:1px 5px;border-radius:9999px;background:var(--s3);color:var(--t3)}'
W '.nb-ct.d{background:var(--rs);color:var(--rd)}'
W '.sb-ft{padding:8px 8px 14px;border-top:1px solid var(--sbbd)}'
W '.sb-fb{display:flex;align-items:center;gap:7px;width:100%;padding:7px 10px;border-radius:7px;border:none;background:transparent;color:var(--t3);font-size:12px;font-weight:500;cursor:pointer;font-family:var(--f);transition:var(--tr);text-align:left;margin-bottom:1px}'
W '.sb-fb:hover{background:var(--sbh);color:var(--t1)}'
W '.mw{margin-left:var(--sw);flex:1;display:flex;flex-direction:column;height:100vh;overflow:hidden}'
W '.topbar{height:var(--hh);min-height:var(--hh);background:var(--s);border-bottom:1px solid var(--b);display:flex;align-items:center;padding:0 26px;gap:14px;position:sticky;top:0;z-index:30}'
W '.tb-ttl{font-size:15px;font-weight:700;color:var(--t1);flex:1}.tb-sub{font-size:11px;color:var(--t3);font-weight:400;margin-top:1px}'
W '.tb-acts{display:flex;align-items:center;gap:7px}'
W '.btn{display:inline-flex;align-items:center;gap:5px;padding:6px 13px;border-radius:9999px;font-size:12px;font-weight:600;cursor:pointer;font-family:var(--f);border:1px solid var(--b);background:var(--s2);color:var(--t2);transition:var(--tr);white-space:nowrap}'
W '.btn:hover{background:var(--s3);color:var(--t1)}.btn.bl{background:var(--ac);color:#fff;border-color:var(--ac)}.btn.bl:hover{opacity:.88}'
W '.cs{flex:1;overflow-y:auto;padding:22px 26px 30px}.cs::-webkit-scrollbar{width:5px}.cs::-webkit-scrollbar-thumb{background:var(--b);border-radius:9999px}'
W '.panel{display:none}.panel.act{display:block;animation:fi .18s ease}@keyframes fi{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:translateY(0)}}'
W '.ogrid{display:grid;grid-template-columns:1fr 385px;gap:18px;margin-bottom:20px;align-items:start}'
W '.hcard{background:var(--s);border:1px solid var(--b);border-radius:20px;padding:26px 26px 22px;box-shadow:var(--sh)}'
W '.hbrow{display:inline-flex;align-items:center;gap:5px;font-size:11px;font-weight:700;color:var(--ac);background:var(--ag);border:1px solid var(--ab);padding:3px 9px;border-radius:9999px;margin-bottom:12px}'
W '.hhead{font-size:30px;font-weight:800;color:var(--t1);letter-spacing:-.8px;line-height:1.15;margin-bottom:18px}'
W '.hstats{display:grid;grid-template-columns:1fr 1fr;gap:10px}'
W '.hst{background:var(--s2);border:1px solid var(--b);border-radius:10px;padding:11px 13px}'
W '.hst-l{font-size:10.5px;font-weight:600;color:var(--t3);margin-bottom:3px}'
W '.hst-v{font-family:var(--m);font-size:16px;font-weight:800;color:var(--t1)}.hst-v.g{color:var(--gr)}.hst-v.r{color:var(--rd)}'
W '.cpanel{background:var(--s);border:1px solid var(--b);border-radius:20px;padding:18px;box-shadow:var(--sh)}'
W '.cp-ttl{font-size:11px;font-weight:700;color:var(--t3);text-transform:uppercase;letter-spacing:.5px;margin-bottom:14px}'
W '.cstack{display:flex;flex-direction:column;gap:10px}'
W '.cc{width:100%;height:150px;border-radius:14px;padding:14px 16px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;cursor:pointer;transition:transform .2s,box-shadow .2s;box-shadow:0 8px 22px rgba(0,0,0,.2);border:1px solid rgba(255,255,255,.1)}'
W '.cc:hover{transform:translateY(-2px);box-shadow:0 14px 32px rgba(0,0,0,.28)}'
W '.cc-bca{background:linear-gradient(135deg,#003087 0%,#0060af 55%,#1e88e5 100%)}'
W '.cc-xbet{background:linear-gradient(135deg,#111 0%,#1c1c1c 50%,#2d2d2d 100%)}'
W '.cc-shop{background:linear-gradient(135deg,#ee4d2d 0%,#f97316 60%,#ff9800 100%)}'
W '.cd{position:absolute;border-radius:50%;background:#fff;opacity:.08}.cd1{width:180px;height:180px;right:-40px;top:-50px}.cd2{width:110px;height:110px;right:35px;top:16px}'
W '.ctop{display:flex;justify-content:space-between;align-items:flex-start;position:relative;z-index:2}.cbot{position:relative;z-index:2}'
W '.cnr{font-family:var(--m);font-size:12.5px;font-weight:500;color:rgba(255,255,255,.85);letter-spacing:2px;margin-bottom:6px}'
W '.cmr{display:flex;justify-content:space-between;align-items:flex-end}'
W '.chl{font-size:10px;font-weight:700;color:rgba(255,255,255,.9);text-transform:uppercase;letter-spacing:.5px}'
W '.cex{font-size:9px;color:rgba(255,255,255,.6);text-align:right}'
W '.cam{font-family:var(--m);font-size:12px;font-weight:700;color:rgba(255,255,255,.95)}'
W '.shdr{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}'
W '.sttl{font-size:15px;font-weight:700;color:var(--t1)}'
W '.ftabs{display:flex;gap:2px;border-bottom:1px solid var(--b);margin-bottom:14px}'
W '.ftab{padding:7px 13px;border:none;background:none;font-family:var(--f);font-size:12.5px;font-weight:500;color:var(--t3);cursor:pointer;border-bottom:2px solid transparent;margin-bottom:-1px;transition:var(--tr)}'
W '.ftab:hover{color:var(--t1)}.ftab.act{color:var(--ac);font-weight:600;border-bottom-color:var(--ac)}'
W '.txg{display:grid;grid-template-columns:1fr 1fr;gap:3px}'
W '.txi{display:flex;align-items:center;justify-content:space-between;padding:9px 11px;border-radius:7px;cursor:pointer;transition:var(--tr)}'
W '.txi:hover{background:var(--s2)}'
W '.txl{display:flex;align-items:center;gap:10px;min-width:0}'
W '.txic{width:38px;height:38px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:800;color:#fff;flex-shrink:0}'
W '.txn{font-size:13px;font-weight:600;color:var(--t1);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:130px}'
W '.txs{font-size:11px;color:var(--t3);margin-top:1px}.txr{text-align:right;flex-shrink:0}'
W '.txa{font-family:var(--m);font-size:13px;font-weight:700;color:var(--t1);white-space:nowrap}.txa.c{color:var(--gr)}.txa.d{color:var(--rd)}'
W '.txd{font-size:10.5px;color:var(--t4);margin-top:1px}'
W '.val{display:inline-flex;align-items:center;gap:4px;font-size:12.5px;font-weight:600;color:var(--t3);cursor:pointer;padding:3px 7px;border-radius:5px}'
W '.val:hover{color:var(--t1);background:var(--s2)}'
W '.kgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(185px,1fr));gap:12px;margin-bottom:18px}'
W '.kc{background:var(--s);border:1px solid var(--b);border-radius:15px;padding:14px 16px;box-shadow:var(--sh)}'
W '.kl{font-size:10.5px;font-weight:700;color:var(--t3);text-transform:uppercase;letter-spacing:.4px;margin-bottom:5px}'
W '.kv{font-family:var(--m);font-size:19px;font-weight:800;color:var(--t1);line-height:1}.kv.g{color:var(--gr)}.kv.r{color:var(--rd)}.kv.b{color:var(--ac)}.kv.a{color:var(--am)}'
W '.ks{font-size:11px;color:var(--t3);margin-top:4px}'
W '.cg2{display:grid;grid-template-columns:1fr 1fr;gap:13px;margin-bottom:17px}.cg1{margin-bottom:17px}'
W '.cb{background:var(--s);border:1px solid var(--b);border-radius:15px;padding:15px 17px;box-shadow:var(--sh)}'
W '.cb-t{font-size:13.5px;font-weight:700;color:var(--t1);margin-bottom:2px}.cb-s{font-size:11px;color:var(--t3);margin-bottom:12px}'
W '.cw{position:relative;height:225px}.cw.t{height:260px}'
W '.tlbr{display:flex;flex-wrap:wrap;gap:7px;align-items:center;margin-bottom:12px}'
W '.inp{flex:1;min-width:200px;background:var(--s);border:1px solid var(--b);border-radius:7px;padding:7px 11px;color:var(--t1);font-size:12.5px;font-family:var(--f);outline:none;transition:var(--tr)}'
W '.inp:focus{border-color:var(--ac);box-shadow:0 0 0 3px var(--ag)}'
W '.sel{background:var(--s);border:1px solid var(--b);border-radius:7px;padding:7px 11px;color:var(--t1);font-size:12.5px;font-family:var(--f);cursor:pointer;outline:none}'
W '.tw{background:var(--s);border:1px solid var(--b);border-radius:15px;overflow:hidden;overflow-x:auto;box-shadow:var(--sh)}'
W 'table{width:100%;border-collapse:collapse}'
W 'thead th{background:var(--s2);padding:9px 13px;font-size:10.5px;font-weight:700;color:var(--t3);text-transform:uppercase;letter-spacing:.4px;border-bottom:1px solid var(--b);white-space:nowrap;cursor:pointer;text-align:left}'
W 'thead th:hover{background:var(--s3);color:var(--t1)}'
W 'tbody td{padding:9px 13px;border-bottom:1px solid var(--b);color:var(--t1);font-size:12px;vertical-align:middle}'
W 'tbody tr:last-child td{border-bottom:none}tbody tr:hover td{background:var(--s2);cursor:pointer}'
W '.pill{display:inline-flex;align-items:center;padding:2px 7px;border-radius:9999px;font-size:10.5px;font-weight:700;white-space:nowrap}'
W '.pill.c{background:var(--gs);color:var(--gr)}.pill.d{background:var(--rs);color:var(--rd)}.pill.w{background:var(--as);color:var(--am)}.pill.i{background:var(--ag);color:var(--ac)}.pill.g{background:var(--s3);color:var(--t3)}.pill.p{background:var(--ps);color:var(--pu)}'
W '.tft{display:flex;justify-content:space-between;align-items:center;padding:10px 15px;background:var(--s2);border-top:1px solid var(--b);font-size:11.5px;color:var(--t3)}'
W '.mbo{display:none;position:fixed;inset:0;background:rgba(0,0,0,.55);backdrop-filter:blur(6px);z-index:100;align-items:center;justify-content:center;padding:18px}'
W '.mbo.op{display:flex}'
W '.mc{background:var(--s);border:1px solid var(--b);border-radius:20px;max-width:510px;width:100%;padding:22px;box-shadow:0 24px 50px rgba(0,0,0,.3);animation:fi .18s ease}'
W '.mh{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}'
W '.mt{font-size:15px;font-weight:800;color:var(--t1)}'
W '.mx{border:none;background:none;font-size:21px;color:var(--t3);cursor:pointer;line-height:1}'
W '.mr-row{margin-bottom:12px}.mrl{font-size:10px;font-weight:700;color:var(--t4);text-transform:uppercase;letter-spacing:.5px;margin-bottom:3px}'
W '.mrv{font-size:13.5px;font-weight:600;color:var(--t1)}.mrv.b{font-size:20px;font-weight:800}.mrv.g{color:var(--gr)}.mrv.r{color:var(--rd)}'
W '.mrd{background:var(--s2);border:1px solid var(--b);border-radius:7px;padding:9px 11px;font-family:var(--m);font-size:11px;color:var(--t2);word-break:break-all;line-height:1.5}'
W '.wbanner{background:var(--as);border:1px solid rgba(217,119,6,.2);border-radius:15px;padding:14px 17px;display:flex;align-items:flex-start;gap:11px;margin-bottom:17px}'
W '.wt{font-size:14px;font-weight:800;color:var(--am);margin-bottom:2px}.ws{font-size:12px;color:var(--t2)}'
W '</style></head><body>'

# Sidebar
W '<aside class="sidebar">'
W '  <div class="sb-top"><div class="sb-ico"><svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg></div><span class="sb-name">AuditID</span><span class="sb-badge">2023-2026</span></div>'
W '  <div class="sb-user"><div class="sb-av">FF</div><div><div class="sb-un">Fahmi Fahrezy</div><div class="sb-us">BCA 1210931399</div></div></div>'
W '  <nav class="sb-nav">'
W '    <div class="sb-lbl">Menu</div>'
W '    <button class="nb act" onclick="sw(''ov'')"><svg width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>Overview</button>'
W '    <button class="nb" onclick="sw(''bca'')"><svg width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>Mutasi BCA<span class="nb-ct" id="sbCt">1.801</span></button>'
W '    <button class="nb" onclick="sw(''jd'')"><svg width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>Judi Online<span class="nb-ct d">628</span></button>'
W '    <button class="nb" onclick="sw(''pj'')"><svg width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>Pinjol Shopee</button>'
W '    <button class="nb" onclick="sw(''kl'')"><svg width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c3 3 9 3 12 0v-5"/></svg>Biaya Kuliah</button>'
W '    <div class="sb-lbl" style="margin-top:6px">Audit</div>'
W '    <button class="nb" onclick="sw(''an'')"><svg width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>Rekonsiliasi</button>'
W '    <button class="nb" onclick="sw(''lb'')"><svg width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>Buku Besar</button>'
W '  </nav>'
W '  <div class="sb-ft">'
W '    <button class="sb-fb" onclick="tgTm()"><span id="tmEm">&#127769;</span><span id="tmLb">Mode Gelap</span></button>'
W '    <button class="sb-fb" onclick="document.getElementById(''pdfIn'').click()"><svg width="12" height="12" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>Upload PDF</button>'
W '    <button class="sb-fb" onclick="expCsv()"><svg width="12" height="12" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>Export CSV</button>'
W '  </div>'
W '</aside>'

# Main wrapper + topbar
W '<div class="mw">'
W '  <header class="topbar">'
W '    <div><div class="tb-ttl" id="tpTl">Selamat datang, Fahmi Fahrezy.</div><div class="tb-sub" id="tpSb">Audit Finansial Terpadu 2023-2026</div></div>'
W '    <div class="tb-acts"><button class="btn" onclick="tgTm()"><span id="tpTmEm">&#127769;</span>&nbsp;Dark Mode</button><button class="btn bl" onclick="expCsv()">Export CSV</button></div>'
W '  </header>'
W '  <div class="cs">'

# OVERVIEW PANEL
W '  <section id="p-ov" class="panel act">'
W '    <div class="ogrid">'
W '      <div class="hcard">'
W '        <div class="hbrow"><svg width="11" height="11" viewBox="0 0 24 24" fill="currentColor"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>Audit Finansial Terpadu 2023-2026</div>'
W '        <div class="hhead">Ringkasan Arus Kas &amp;<br>Beban Finansial.</div>'
W '        <div class="hstats">'
W '          <div class="hst"><div class="hst-l">Total Masuk BCA (CR)</div><div class="hst-v g">Rp 167,23 Jt</div></div>'
W '          <div class="hst"><div class="hst-l">Total Keluar BCA (DB)</div><div class="hst-v r">Rp 167,22 Jt</div></div>'
W '          <div class="hst"><div class="hst-l">Kerugian Judi 1xBet</div><div class="hst-v r">-Rp 4,76 Jt</div></div>'
W '          <div class="hst"><div class="hst-l">Total Beban Finansial</div><div class="hst-v r">Rp 48,32 Jt</div></div>'
W '        </div>'
W '      </div>'
# Cards panel with chip SVG
W '      <div class="cpanel">'
W '        <div class="cp-ttl">Rekening &amp; Platform</div>'
W '        <div class="cstack">'

# BCA Card with chip
W '          <div class="cc cc-bca" onclick="sw(''bca'')">'
W '            <div class="cd cd1"></div><div class="cd cd2"></div>'
W '            <div class="ctop">'
W '              <svg height="20" viewBox="0 0 90 28" xmlns="http://www.w3.org/2000/svg"><text x="0" y="22" font-family="Arial" font-weight="900" font-size="24" fill="white">BCA</text></svg>'
W '              <svg width="34" height="26" viewBox="0 0 34 26" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="34" height="26" rx="3" fill="#D4AF37" opacity=".85"/><rect x="12" y="0" width="10" height="26" fill="#C5A028" opacity=".55"/><rect x="0" y="8" width="34" height="10" fill="#C5A028" opacity=".55"/><rect x="3" y="3" width="28" height="20" rx="2" fill="none" stroke="#B8960C" stroke-width="1"/><rect x="12" y="8" width="10" height="10" rx="1" fill="#B8960C" opacity=".75"/></svg>'
W '            </div>'
W '            <div class="cbot"><div class="cnr">1210  9313  99</div><div class="cmr"><div><div class="chl">Fahmi Fahrezy</div><div class="cex">41 Bulan Terdata</div></div><div><div class="cam">+Rp 167,23 Jt</div><div class="cex">Total CR</div></div></div></div>'
W '          </div>'

# 1xBet Card
W '          <div class="cc cc-xbet" onclick="sw(''jd'')">'
W '            <div class="cd cd1"></div><div class="cd cd2"></div>'
W '            <div class="ctop">'
W '              <svg height="18" viewBox="0 0 90 26" xmlns="http://www.w3.org/2000/svg"><text x="0" y="20" font-family="Arial" font-weight="900" font-size="22" fill="white">1xBet</text></svg>'
W '              <svg width="34" height="26" viewBox="0 0 34 26" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="34" height="26" rx="3" fill="#888" opacity=".55"/><rect x="12" y="0" width="10" height="26" fill="#666" opacity=".55"/><rect x="0" y="8" width="34" height="10" fill="#666" opacity=".55"/><rect x="3" y="3" width="28" height="20" rx="2" fill="none" stroke="#555" stroke-width="1"/><rect x="12" y="8" width="10" height="10" rx="1" fill="#555" opacity=".75"/></svg>'
W '            </div>'
W '            <div class="cbot"><div class="cnr" style="color:rgba(251,113,113,.8)">628 DEPO  -  73 WD</div><div class="cmr"><div><div class="chl">Judi Online</div><div class="cex">ROI -26.6%</div></div><div><div class="cam" style="color:#f87171">-Rp 4,76 Jt</div><div class="cex">Net Loss</div></div></div></div>'
W '          </div>'

# Shopee Card
W '          <div class="cc cc-shop" onclick="sw(''pj'')">'
W '            <div class="cd cd1"></div><div class="cd cd2"></div>'
W '            <div class="ctop">'
W '              <svg height="20" viewBox="0 0 120 28" xmlns="http://www.w3.org/2000/svg"><text x="0" y="22" font-family="Arial" font-weight="900" font-size="23" fill="white">Shopee</text></svg>'
W '              <svg width="34" height="26" viewBox="0 0 34 26" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="34" height="26" rx="3" fill="#D4AF37" opacity=".7"/><rect x="12" y="0" width="10" height="26" fill="#C5A028" opacity=".5"/><rect x="0" y="8" width="34" height="10" fill="#C5A028" opacity=".5"/><rect x="3" y="3" width="28" height="20" rx="2" fill="none" stroke="#B8960C" stroke-width="1"/><rect x="12" y="8" width="10" height="10" rx="1" fill="#B8960C" opacity=".65"/></svg>'
W '            </div>'
W '            <div class="cbot"><div class="cnr">SPinjam + SPayLater</div><div class="cmr"><div><div class="chl">Fahmi Fahrezy</div><div class="cex">7 Pos Pinjaman</div></div><div><div class="cam">~Rp 4,77 Jt</div><div class="cex">Kewajiban</div></div></div></div>'
W '          </div>'

W '        </div></div>'  # end cstack + cpanel
W '    </div>'  # end ogrid

# Recent transactions section
W '    <div style="background:var(--s);border:1px solid var(--b);border-radius:16px;padding:16px 18px;box-shadow:var(--sh)">'
W '      <div class="shdr"><div class="sttl">Transaksi Terkini</div><span class="val" onclick="sw(''lb'')">Lihat semua &#8594;</span></div>'
W '      <div class="ftabs"><button class="ftab act" onclick="fTx(''all'',this)">Semua</button><button class="ftab" onclick="fTx(''bca'',this)">BCA</button><button class="ftab" onclick="fTx(''1xbet'',this)">1xBet</button><button class="ftab" onclick="fTx(''pinjol'',this)">Pinjol</button></div>'
W '      <div class="txg" id="txGrid"></div>'
W '    </div>'

# 2 charts
W '    <div class="cg2" style="margin-top:18px">'
W '      <div class="cb"><div class="cb-t">Komposisi Beban Finansial</div><div class="cb-s">Kuliah vs Judi vs Pinjol</div><div class="cw"><canvas id="cDonut"></canvas></div></div>'
W '      <div class="cb"><div class="cb-t">Perbandingan Nominal</div><div class="cb-s">Judi kerugian vs biaya SPP</div><div class="cw"><canvas id="cCompare"></canvas></div></div>'
W '    </div>'
W '  </section>'

# BCA PANEL
W '  <section id="p-bca" class="panel">'
W '    <div class="kgrid"><div class="kc"><div class="kl">Total Masuk (CR)</div><div class="kv g">Rp 167.236.850</div><div class="ks">41 Bulan Apr 2023 - Agu 2026</div></div><div class="kc"><div class="kl">Total Keluar (DB)</div><div class="kv r">Rp 167.226.502</div><div class="ks">1.801 Transaksi</div></div><div class="kc"><div class="kl">Sisa Saldo</div><div class="kv">+Rp 10.348</div><div class="ks">Selisih Audit: Rp 0</div></div><div class="kc"><div class="kl">Suspect Judol QRIS</div><div class="kv r">Rp 3.160.248</div><div class="ks">55 Transaksi</div></div></div>'
W '    <div class="cg1"><div class="cb"><div class="cb-t">Arus Kas Bulanan BCA (Apr 2023 - Agu 2026)</div><div class="cb-s">Uang Masuk vs Uang Keluar per Bulan</div><div class="cw t"><canvas id="cBcaTL"></canvas></div></div></div>'
W '    <div class="tlbr"><input type="text" id="bSrc" class="inp" placeholder="Cari merchant, QRIS, nominal..." oninput="rBca()"><select id="bPer" class="sel" onchange="rBca()"><option value="ALL">Semua Periode</option></select><select id="bTyp" class="sel" onchange="rBca()"><option value="ALL">Semua</option><option value="in">Masuk (CR)</option><option value="out">Keluar (DB)</option><option value="QRIS">QRIS</option><option value="wallet">E-Wallet</option><option value="risk">Suspect Judol</option></select><button class="btn bl" onclick="document.getElementById(''pdfIn'').click()">+ Upload PDF</button></div>'
W '    <div class="tw"><table><thead><tr><th onclick="sBca(''date'')">Tanggal</th><th>Tipe</th><th>Kategori</th><th>Merchant/Pihak</th><th>Keterangan</th><th onclick="sBca(''amount'')" style="text-align:right">Nominal</th></tr></thead><tbody id="bTb"></tbody></table><div class="tft"><span id="bPgi"></span><div style="display:flex;gap:6px"><button class="btn" id="bPrv" onclick="pBca(-1)">Prev</button><button class="btn" id="bNxt" onclick="pBca(1)">Next</button></div></div></div>'
W '  </section>'

# JUDOL PANEL
W '  <section id="p-jd" class="panel">'
W '    <div class="kgrid"><div class="kc"><div class="kl">Modal Disetor</div><div class="kv r">Rp 17.871.421</div><div class="ks">628 deposit</div></div><div class="kc"><div class="kl">WD Berhasil</div><div class="kv g">Rp 13.110.819</div><div class="ks">73 withdrawal</div></div><div class="kc"><div class="kl">Kerugian Bersih</div><div class="kv r">-Rp 4.760.602</div><div class="ks">ROI -26.6%</div></div><div class="kc"><div class="kl">Depo Dini Hari 00-05</div><div class="kv a">229 Transaksi</div><div class="ks">36.5% dari semua depo</div></div></div>'
W '    <div class="cg2"><div class="cb"><div class="cb-t">Akumulasi Kerugian</div><div class="cb-s">Net loss kumulatif sepanjang waktu</div><div class="cw"><canvas id="cCumL"></canvas></div></div><div class="cb"><div class="cb-t">Distribusi Jam Deposit</div><div class="cb-s">Merah = dini hari 00-05</div><div class="cw"><canvas id="cHour"></canvas></div></div></div>'
W '    <div class="tlbr"><input type="text" id="xSrc" class="inp" placeholder="Cari nominal, referensi, kanal..." oninput="rXbt()"><select id="xTyp" class="sel" onchange="rXbt()"><option value="ALL">Semua</option><option value="DEPOSIT">Deposit</option><option value="WITHDRAW">Withdraw</option><option value="WITHDRAW_REQ">Pengajuan WD</option><option value="WITHDRAW_REJECT">WD Ditolak</option></select><select id="xYr" class="sel" onchange="rXbt()"><option value="ALL">Semua Tahun</option><option value="2024">2024</option><option value="2025">2025</option><option value="2026">2026</option></select></div>'
W '    <div class="tw"><table><thead><tr><th onclick="sXbt(''id'')">#</th><th onclick="sXbt(''date'')">Waktu</th><th>Kategori</th><th onclick="sXbt(''amount'')" style="text-align:right">Nominal</th><th>Kanal</th><th>Status</th><th>Keterangan</th></tr></thead><tbody id="xTb"></tbody></table><div class="tft"><span id="xPgi"></span><div style="display:flex;gap:6px"><button class="btn" id="xPrv" onclick="pXbt(-1)">Prev</button><button class="btn" id="xNxt" onclick="pXbt(1)">Next</button></div></div></div>'
W '  </section>'

# PINJOL PANEL
W '  <section id="p-pj" class="panel">'
W '    <div class="wbanner"><div style="font-size:22px">&#9888;&#65039;</div><div><div class="wt">Total Kewajiban Shopee: ~Rp 4.766.903</div><div class="ws">7 pos pinjaman diambil November 2024 saat aktivitas judi online sedang puncak. SPinjam 5x + SPayLater 3 bulan + denda keterlambatan.</div></div></div>'
W '    <div class="kgrid" id="pjGrid"></div>'
W '    <div class="cg2"><div class="cb"><div class="cb-t">Komposisi Pinjol</div><div class="cb-s">SPinjam vs SPayLater</div><div class="cw"><canvas id="cPjPie"></canvas></div></div><div class="cb"><div class="cb-t">Timeline Penarikan</div><div class="cb-s">Semua pinjaman dalam 2 minggu</div><div class="cw"><canvas id="cPjTl"></canvas></div></div></div>'
W '  </section>'

# KULIAH PANEL
W '  <section id="p-kl" class="panel">'
W '    <div class="kgrid"><div class="kc"><div class="kl">Total SPP (7 Semester)</div><div class="kv b">Rp 26.600.000</div><div class="ks">7 x Rp 3.800.000</div></div><div class="kc"><div class="kl">Total DPP (9 Angsuran)</div><div class="kv b">Rp 9.750.000</div><div class="ks">DPP 1 s.d. DPP 9</div></div><div class="kc"><div class="kl">Biaya Tambahan</div><div class="kv">Rp 2.450.000</div><div class="ks">Sertifikasi + Orientasi + TA</div></div><div class="kc"><div class="kl">Total Keseluruhan</div><div class="kv b">Rp 38.800.000</div><div class="ks">7 Semester Penuh</div></div></div>'
W '    <div class="cg2"><div class="cb"><div class="cb-t">Komposisi Biaya Kuliah</div><div class="cb-s">SPP vs DPP vs Tambahan</div><div class="cw"><canvas id="cKlPie"></canvas></div></div><div class="cb"><div class="cb-t">Biaya per Semester</div><div class="cb-s">Semester 1 paling mahal</div><div class="cw"><canvas id="cKlBar"></canvas></div></div></div>'
W '    <div class="tw"><table><thead><tr><th>Semester</th><th>Komponen</th><th>Detail</th><th style="text-align:right">Nominal</th></tr></thead><tbody id="klTb"></tbody></table></div>'
W '  </section>'

# ANALYTICS PANEL
W '  <section id="p-an" class="panel">'
W '    <div class="kgrid"><div class="kc"><div class="kl">Total Beban</div><div class="kv r">Rp 48.327.505</div><div class="ks">Judi + Pinjol + Kuliah</div></div><div class="kc"><div class="kl">% dari Uang Masuk BCA</div><div class="kv a">28.9%</div><div class="ks">Hampir 1/3 uang masuk</div></div><div class="kc"><div class="kl">Selisih Audit BCA</div><div class="kv g">Rp 0</div><div class="ks">CR - DB = Rp 10.348</div></div><div class="kc"><div class="kl">Suspect QRIS Judol</div><div class="kv r">Rp 3.160.248</div><div class="ks">55 transaksi di BCA</div></div></div>'
W '    <div class="cg2"><div class="cb"><div class="cb-t">Kanal Deposit 1xBet</div><div class="cb-s">E-Wallet vs Transfer Bank</div><div class="cw"><canvas id="cChan"></canvas></div></div><div class="cb"><div class="cb-t">Frekuensi Judi per Hari</div><div class="cb-s">Distribusi dalam seminggu</div><div class="cw"><canvas id="cDoW"></canvas></div></div></div>'
W '    <div class="tw"><table><thead><tr><th>Tahun</th><th>Bulan</th><th>BCA Masuk</th><th>BCA Keluar</th><th>Depo 1xBet</th><th>WD 1xBet</th><th>Net Judi</th></tr></thead><tbody id="anTb"></tbody></table></div>'
W '  </section>'

# LEDGER PANEL
W '  <section id="p-lb" class="panel">'
W '    <div class="tlbr"><input type="text" id="lSrc" class="inp" placeholder="Cari semua sumber (BCA, 1xBet, Shopee, Kuliah)..." oninput="rLed()"><select id="lSou" class="sel" onchange="rLed()"><option value="ALL">Semua Sumber</option><option value="BCA">BCA</option><option value="1XBET">1xBet</option><option value="PINJOL">Pinjol</option><option value="KULIAH">Kuliah</option></select><select id="lYr" class="sel" onchange="rLed()"><option value="ALL">Semua Tahun</option><option value="2023">2023</option><option value="2024">2024</option><option value="2025">2025</option><option value="2026">2026</option></select><select id="lTyp" class="sel" onchange="rLed()"><option value="ALL">Semua</option><option value="in">Pemasukan</option><option value="out">Pengeluaran</option></select></div>'
W '    <div class="tw"><table><thead><tr><th onclick="sLed(''date'')">Tanggal</th><th>Sumber</th><th>Kategori</th><th>Pihak</th><th>Keterangan</th><th onclick="sLed(''amount'')" style="text-align:right">Nominal</th></tr></thead><tbody id="lTb"></tbody></table><div class="tft"><span id="lPgi"></span><div style="display:flex;gap:6px"><button class="btn" id="lPrv" onclick="pLed(-1)">Prev</button><button class="btn" id="lNxt" onclick="pLed(1)">Next</button></div></div></div>'
W '  </section>'

W '  </div></div>'  # end .cs and .mw

# MODAL
W '<div id="mbo" class="mbo" onclick="if(event.target===this)cMod()">'
W '  <div class="mc"><div class="mh"><div class="mt" id="mTtl">Detail Transaksi</div><button class="mx" onclick="cMod()">x</button></div>'
W '  <div class="mr-row"><div class="mrl">Tanggal</div><div class="mrv mono" id="mDt"></div></div>'
W '  <div class="mr-row"><div class="mrl">Nominal</div><div class="mrv b" id="mAmt"></div></div>'
W '  <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px"><div><div class="mrl">Kategori &amp; Sumber</div><div class="mrv" id="mCat"></div></div><div><div class="mrl">Status</div><div id="mStt"></div></div></div>'
W '  <div class="mr-row"><div class="mrl">Merchant / Pihak</div><div class="mrv" id="mPty"></div></div>'
W '  <div><div class="mrl" style="margin-bottom:5px">Deskripsi Lengkap</div><div class="mrd" id="mDsc"></div></div>'
W '  </div></div>'

W '<input type="file" id="pdfIn" accept=".pdf" multiple style="display:none" onchange="upPdf(event)">'

# JavaScript
W '<script>'
W 'const PS=25;'
W 'let theme=localStorage.getItem("ATM")||"light";'
W 'let bcaD={stmts:[],txs:[]};'
W 'let mRows=[];'
W 'let bSCol="date",bSAsc=false,bPg=1;'
W 'let xSCol="date",xSAsc=false,xPg=1;'
W 'let lSCol="date",lSAsc=false,lPg=1;'
W 'let actTab="ov";'
W 'const MO=["Jan","Feb","Mar","Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des"];'
W 'const MM={JAN:0,JANUARI:0,FEB:1,FEBRUARI:1,MAR:2,MARET:2,APR:3,APRIL:3,MEI:4,MAY:4,JUN:5,JUNI:5,JUL:6,JULI:6,AGU:7,AGUSTUS:7,AUG:7,SEP:8,SEPTEMBER:8,OKT:9,OKTOBER:9,OCT:9,NOV:10,NOVEMBER:10,DES:11,DESEMBER:11,DEC:11};'
W 'function fI(n){return"Rp "+Math.round(Number(n||0)).toLocaleString("id-ID")}'
W 'function pM(v){if(!v)return 0;let s=String(v).replace(/[^\d,.-]/g,"");if(!s)return 0;const hc=s.includes(","),hd=s.includes(".");if(hc&&hd){const lc=s.lastIndexOf(","),ld=s.lastIndexOf(".");s=ld>lc?s.replace(/,/g,""):s.replace(/\./g,"").replace(",",".")}else if(hc){const p=s.split(",");s=p[p.length-1].length===2?p.slice(0,-1).join("")+"."+p[p.length-1]:s.replace(/,/g,"")}else if(hd){const p=s.split(".");if(p.length>2||p[p.length-1].length===3)s=s.replace(/\./g,"")}return Number(s)||0}'
W 'function b64U8(b){const bs=atob(b);const u=new Uint8Array(bs.length);for(let i=0;i<bs.length;i++)u[i]=bs.charCodeAt(i);return u}'
W 'function es(s){return String(s||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}'
W 'function apTm(t){theme=t;document.documentElement.setAttribute("data-theme",t);localStorage.setItem("ATM",t);const d=t==="dark";document.getElementById("tmEm").textContent=d?"☀️":"🌙";document.getElementById("tmLb").textContent=d?"Mode Terang":"Mode Gelap";document.getElementById("tpTmEm").textContent=d?"☀️":"🌙"}'
W 'function tgTm(){apTm(theme==="light"?"dark":"light")}'

W 'const TM={ov:{t:"Selamat datang, Fahmi Fahrezy.",s:"Audit Finansial Terpadu 2023-2026"},bca:{t:"Mutasi BCA",s:"41 Bulan - 1.801 Transaksi"},jd:{t:"Judi Online 1xBet",s:"628 Deposit - Net Loss -Rp 4.760.602"},pj:{t:"Pinjol Shopee",s:"SPinjam & SPayLater - Total ~Rp 4.766.903"},kl:{t:"Biaya Kuliah",s:"7 Semester - Total Rp 38.800.000"},an:{t:"Rekonsiliasi Silang",s:"Komparasi BCA vs 1xBet vs Pinjol"},lb:{t:"Buku Besar Gabungan",s:"Seluruh transaksi dari semua sumber"}};'
W 'function sw(tab){actTab=tab;document.querySelectorAll(".panel").forEach(p=>p.classList.remove("act"));document.querySelectorAll(".nb").forEach(b=>b.classList.remove("act"));const p=document.getElementById("p-"+tab);if(p)p.classList.add("act");const idx=["ov","bca","jd","pj","kl","an","lb"].indexOf(tab);const bs=document.querySelectorAll(".nb");if(bs[idx])bs[idx].classList.add("act");const m=TM[tab]||{};document.getElementById("tpTl").textContent=m.t||tab;document.getElementById("tpSb").textContent=m.s||"";if(tab==="bca")rBca();if(tab==="jd")rXbt();if(tab==="lb")rLed()}'

# PDF parsing
W 'async function pdfBytes(bytes,fn){'
W '  const pdf=await pdfjsLib.getDocument({data:bytes,disableWorker:true,useWorkerFetch:false,isEvalSupported:false}).promise;'
W '  const pages=[];'
W '  for(let pn=1;pn<=pdf.numPages;pn++){'
W '    const pg=await pdf.getPage(pn);const c=await pg.getTextContent();'
W '    const it=c.items.map(i=>({t:i.str,x:Math.round(i.transform[4]),y:Math.round(i.transform[5])})).filter(i=>i.t.trim());'
W '    it.sort((a,b)=>Math.abs(b.y-a.y)>3?b.y-a.y:a.x-b.x);'
W '    const ln=[];for(const i of it){const L=ln[ln.length-1];if(!L||Math.abs(L.y-i.y)>3)ln.push({y:i.y,p:[i]});else L.p.push(i)}'
W '    pages.push(ln.map(l=>{l.p.sort((a,b)=>a.x-b.x);return l.p.map(p=>p.t).join(" ").replace(/\s+/g," ").trim();}).join("\n"));'
W '  }'
W '  return parseSt(pages.join("\n"),fn);'
W '}'
W 'function parseSt(text,fn){'
W '  const meta=getMeta(text,fn);'
W '  const lines=text.split(/\r?\n/).map(l=>l.trim()).filter(Boolean);'
W '  const txs=[];let cur=null,ad=null;'
W '  for(const raw of lines){'
W '    const line=raw.replace(/\s+/g," ").trim();'
W '    const dm=line.match(/^(\d{2})\/(\d{2})(?:\s+(.+))?$/);'
W '    if(dm){if(cur)txs.push(finTx(cur,meta));ad={day:Number(dm[1]),month:Number(dm[2])-1,year:meta.year};cur={...ad,lines:[dm[3]||""],file:fn};continue}'
W '    if(!cur)continue;'
W '    if(/^(REKENING|KCU|CATATAN|TANGGAL|Bersambung|HALAMAN|MATA UANG)/i.test(line))continue;'
W '    if(/^(MUTASI CR|MUTASI DB|SALDO AKHIR|SALDO AWAL\s*:)/i.test(line))continue;'
W '    cur.lines.push(line);'
W '  }'
W '  if(cur)txs.push(finTx(cur,meta));'
W '  return{txs:txs.filter(Boolean),summary:meta.summary,meta};'
W '}'
W 'function getMeta(text,fn){'
W '  const acct=(text.match(/NO\.?\s*REKENING\s*:?\s*(\d+)/i)||[])[1]||"1210931399";'
W '  const pr=(text.match(/PERIODE\s*:?\s*([A-Z]+)\s+(\d{4})/i)||[]);'
W '  const mn=pr[1]||(Object.keys(MM).find(n=>fn.toUpperCase().includes(n))||"");'
W '  const ym=fn.match(/20\d{2}/);const year=Number(pr[2]||(ym?ym[0]:2024));'
W '  const month=MM[mn.toUpperCase()]??0;'
W '  const pl=mn?`${MO[month]||mn} ${year}`:String(year);'
W '  const mk=`${year}-${String(month+1).padStart(2,"0")}`;'
W '  const nums=exNums(text);'
W '  const summary={file:fn,monthKey:mk,periodLabel:pl,totalIn:pM(nums?.cr||0),totalOut:pM(nums?.db||0),openingBalance:pM(nums?.op||0),endingBalance:pM(nums?.en||0)};'
W '  return{acct,year,month,periodLabel:pl,monthKey:mk,summary};'
W '}'
W 'function exNums(text){'
W '  const ln=text.split(/\r?\n/);let s=-1;'
W '  for(let i=ln.length-1;i>=0;i--){if(/SALDO\s+AWAL\s*:/i.test(ln[i])){s=i;break}}'
W '  if(s<0)return null;'
W '  const b=ln.slice(s,Math.min(s+12,ln.length)).join(" ");'
W '  const v=[...b.matchAll(/\d{1,3}(?:[,.]\d{3})*(?:[,.]\d{2})|\d+(?:[,.]\d{2})/g)].map(m=>m[0]);'
W '  if(v.length<4)return null;'
W '  return{op:v[0],cr:v[1],db:v[2],en:v[3]};'
W '}'
W 'function finTx(cur,meta){'
W '  const body=cur.lines.join(" ").replace(/\s+/g," ").trim();'
W '  if(!body||/SALDO\s+AWAL/i.test(body))return null;'
W '  const isDB=/\bDB\b/i.test(body);'
W '  const aR=/(\d{1,3}(?:[,.]\d{3})*(?:[,.]\d{2})|\d+(?:[,.]\d{2}))(?:\s*DB)?/g;'
W '  const ams=[...body.matchAll(aR)];if(!ams.length)return null;'
W '  let am=ams[0];if(isDB)am=ams.find(m=>/\bDB\b/i.test(body.slice(m.index,m.index+m[0].length+4)))||am;'
W '  else if(ams.length>1)am=/TRSF|BI-FAST|SETORAN|CDM/i.test(body)?ams[0]:(ams[1]||ams[0]);'
W '  const amount=pM(am[1]);const type=isDB?"out":"in";'
W '  const dk=`${cur.year}-${String(cur.month+1).padStart(2,"0")}-${String(cur.day).padStart(2,"0")}`;'
W '  const dd=`${String(cur.day).padStart(2,"0")}/${String(cur.month+1).padStart(2,"0")}/${cur.year}`;'
W '  const cd=body.replace(aR," ").replace(/\bCBG\b|\bMUTASI\b|\bSALDO\b/gi," ").replace(/\s+/g," ").trim();'
W '  const party=exPty(cd||body);const cat=catTx(cd||body,type,party);'
W '  return{id:`BCA-${dk}-${Math.round(amount)}`,source:"BCA",date:dk,displayDate:dd,monthKey:`${cur.year}-${String(cur.month+1).padStart(2,"0")}`,year:cur.year,type,amount,party,category:cat,description:cd||body,riskFlagged:(cat==="QRIS"&&isRisk(party)),iconColor:"#0060af",iconLabel:"BCA"};'
W '}'
W 'function exPty(d){'
W '  const t=d.replace(/\s+/g," ").trim();'
W '  const q=t.match(/QR\s*\d+\s+0+\.00\s*([A-Z0-9][A-Z0-9 ._-]{2,40})/i);if(q)return cPty(q[1]);'
W '  const ke=t.match(/TRANSFER\s+KE\s+\d+\s+([A-Z][A-Z\s.''-]{3,40})/i);if(ke)return cPty(ke[1]);'
W '  const dr=t.match(/TRANSFER\s+DR\s+\d+\s+([A-Z][A-Z\s.''-]{3,40})/i);if(dr)return cPty(dr[1]);'
W '  const w=t.match(/\b(GO-PAY CUSTO|GOPAY|DANA|SHOPEEPAY|SHOPEE|OVO|LINKAJA)\b/i);if(w)return cPty(w[0]);'
W '  const m=t.match(/\b(ALFAMRT|ALFAMART|INDOMARET|EDC Mini-AT|DOMPET ANAK BANGSA)[A-Z0-9\s.-]*/i);if(m)return cPty(m[0]);'
W '  const ws=t.split(" ").filter(p=>/[A-Z]/i.test(p)&&!/^\d/.test(p));'
W '  return ws.length>=2?cPty(ws.slice(-4).join(" ")):"BCA Mutation";'
W '}'
W 'function cPty(v){return String(v||"").replace(/^\/+/,"").replace(/\bTGL:.*$/i,"").replace(/\bDB\b/gi,"").replace(/\s+/g," ").trim()||"BCA Party"}'
W 'function catTx(d,type,party){'
W '  const t=(d+" "+party).toLowerCase();'
W '  if(t.includes("qr ")||t.includes("qris"))return"QRIS";'
W '  if(t.includes("tarikan atm")||t.includes("tarik tunai"))return"ATM";'
W '  if(t.includes("biaya adm"))return"Admin";'
W '  if(t.includes("dana")||t.includes("gopay")||t.includes("go-pay")||t.includes("shopee")||t.includes("ovo")||t.includes("linkaja"))return"E-Wallet";'
W '  if(t.includes("trsf")||t.includes("transfer")||t.includes("bi-fast"))return type==="in"?"Transfer Masuk":"Transfer Keluar";'
W '  if(t.includes("alfamart")||t.includes("indomaret"))return"Belanja";'
W '  return type==="in"?"Masuk Lain":"Keluar Lain";'
W '}'
W 'function isRisk(p){const t=p.toLowerCase();return["obsian","soulshard","slot","bet","game","craft","topup"].some(w=>t.includes(w))}'

# Main init
W 'async function init(){'
W '  apTm(theme);'
W '  if(window.PDF_BASE64_FILES){'
W '    const nms=Object.keys(window.PDF_BASE64_FILES);'
W '    const sts=[];let txs=[];'
W '    for(const n of nms){try{const r=await pdfBytes(b64U8(window.PDF_BASE64_FILES[n]),n);sts.push({file:n,monthKey:r.meta.monthKey,periodLabel:r.meta.periodLabel,sum:r.summary,txc:r.txs.length});txs=txs.concat(r.txs);}catch(e){console.warn("PDF err",n,e)}}'
W '    txs.sort((a,b)=>a.date.localeCompare(b.date));sts.sort((a,b)=>a.monthKey.localeCompare(b.monthKey));'
W '    bcaD={stmts:sts,txs};'
W '    const sel=document.getElementById("bPer");if(sel)sel.innerHTML=''<option value="ALL">Semua (41 Bln)</option>''+sts.map(s=>`<option value="${s.monthKey}">${s.periodLabel}</option>`).join("");'
W '    document.getElementById("sbCt").textContent=txs.length.toLocaleString("id-ID");'
W '  }'
W '  mRows=[];'
W '  bcaD.txs.forEach(t=>mRows.push({...t}));'
W '  if(window.XBET_DATA)window.XBET_DATA.forEach(x=>mRows.push({id:`1XBET-${x.id}`,source:"1XBET",date:x.isoDate,displayDate:x.date,year:x.year,type:x.type==="DEPOSIT"?"out":(x.type==="WITHDRAW"?"in":"req"),category:`1xBet ${x.category}`,party:`1xBet (${x.channel})`,description:x.rawText,amount:x.amount,iconColor:"#1c1c1c",iconLabel:"1X"}));'
W '  [{d:"2024-11-09",dc:"09/11/2024",a:471107},{d:"2024-11-10",dc:"10/11/2024",a:471107},{d:"2024-11-11",dc:"11/11/2024",a:461683},{d:"2024-11-11",dc:"11/11/2024",a:942206},{d:"2024-11-14",dc:"14/11/2024",a:942206},{d:"2024-11-22",dc:"22/11/2024",a:981947},{d:"2025-01-15",dc:"15/01/2025",a:496647}].forEach((p,i)=>mRows.push({id:`PINJOL-${i+1}`,source:"PINJOL",date:p.d,displayDate:p.dc,year:Number(p.d.split("-")[0]),type:"out",category:"Shopee Pinjol",party:"Shopee Financial",description:["SPinjam 09 Nov","SPinjam 10 Nov","SPinjam 11 Nov 500rb","SPinjam 11 Nov 1Jt","SPinjam 14 Nov 1Jt","SPinjam 22 Nov","SPayLater Jan-Mar 2025"][i],amount:p.a,iconColor:"#ee4d2d",iconLabel:"SP"}));'
W '  [{d:"2023-08-01",dc:"01/08/2023",a:10250000,s:"Sem 1"},{d:"2024-02-01",dc:"01/02/2024",a:5800000,s:"Sem 2"},{d:"2024-08-01",dc:"01/08/2024",a:5300000,s:"Sem 3"},{d:"2025-02-01",dc:"01/02/2025",a:5300000,s:"Sem 4"},{d:"2025-08-01",dc:"01/08/2025",a:3800000,s:"Sem 5"},{d:"2026-02-01",dc:"01/02/2026",a:3800000,s:"Sem 6"},{d:"2026-08-01",dc:"01/08/2026",a:4550000,s:"Sem 7"}].forEach((k,i)=>mRows.push({id:`KULIAH-${i+1}`,source:"KULIAH",date:k.d,displayDate:k.dc,year:Number(k.d.split("-")[0]),type:"out",category:"Biaya Kuliah",party:"Universitas",description:k.s,amount:k.a,iconColor:"#7c3aed",iconLabel:"UN"}));'
W '  mRows.sort((a,b)=>a.date.localeCompare(b.date));'
W '  rTx("all");rPjGrid();rKlTb();initCharts();rAn();'
W '}'

# Recent TX
W 'function rTx(f){'
W '  let list=mRows;'
W '  if(f==="bca")list=list.filter(t=>t.source==="BCA");'
W '  else if(f==="1xbet")list=list.filter(t=>t.source==="1XBET");'
W '  else if(f==="pinjol")list=list.filter(t=>t.source==="PINJOL");'
W '  const items=list.slice(-8).reverse();'
W '  document.getElementById("txGrid").innerHTML=items.map(it=>`<div class="txi" onclick="oMod(''${es(it.id)}'')"><div class="txl"><div class="txic" style="background:${it.iconColor}">${it.iconLabel}</div><div><div class="txn">${es(it.party)}</div><div class="txs">${es(it.category)}</div></div></div><div class="txr"><div class="txa ${it.type==="in"?"c":"d"}">${it.type==="in"?"+":"-"}${fI(it.amount)}</div><div class="txd">${it.displayDate}</div></div></div>`).join("");'
W '}'
W 'function fTx(f,btn){document.querySelectorAll(".ftab").forEach(b=>b.classList.remove("act"));btn.classList.add("act");rTx(f)}'

# Pinjol & Kuliah
W 'function rPjGrid(){'
W '  const items=[{l:"SPayLater Jan-Mar 2025",v:"Rp 496.647",s:"Tagihan 3 bln + denda"},{l:"SPinjam 09 Nov 2024",v:"Rp 471.107",s:"Pokok+bunga"},{l:"SPinjam 10 Nov 2024",v:"Rp 471.107",s:"Pokok+bunga"},{l:"SPinjam 11 Nov (500rb)",v:"Rp 461.683",s:"Pagi hari"},{l:"SPinjam 11 Nov (1Jt)",v:"Rp 942.206",s:"Siang hari"},{l:"SPinjam 14 Nov (1Jt)",v:"Rp 942.206",s:"Angsuran 14 Nov"},{l:"SPinjam 22 Nov",v:"~Rp 981.947",s:"Angsuran terlambat"}];'
W '  document.getElementById("pjGrid").innerHTML=items.map(p=>`<div class="kc"><div class="kl" style="display:flex;justify-content:space-between">${p.l}<span class="pill d">Utang</span></div><div class="kv a">${p.v}</div><div class="ks">${p.s}</div></div>`).join("");'
W '}'
W 'function rKlTb(){'
W '  const rows=[["Semester 1","SPP+DPP 1,2,3+Tambahan","Sertifikasi+Orientasi+DPP 1,2,3+SPP","Rp 10.250.000"],["Semester 2","SPP+DPP 4,5","DPP 4,5+SPP","Rp 5.800.000"],["Semester 3","SPP+DPP 6,7","DPP 6,7+SPP","Rp 5.300.000"],["Semester 4","SPP+DPP 8,9","DPP 8,9+SPP","Rp 5.300.000"],["Semester 5","SPP","SPP penuh","Rp 3.800.000"],["Semester 6","SPP","SPP penuh","Rp 3.800.000"],["Semester 7","SPP+Tugas Akhir","SPP+TA","Rp 4.550.000"],["TOTAL","7 Semester","SPP 7x+DPP 9x+Tambahan","<strong>Rp 38.800.000</strong>"]];'
W '  document.getElementById("klTb").innerHTML=rows.map(r=>`<tr><td style="font-weight:700">${r[0]}</td><td><span class="pill p">${r[1]}</span></td><td style="color:var(--t2)">${r[2]}</td><td class="mono" style="text-align:right;font-weight:700">${r[3]}</td></tr>`).join("");'
W '}'

# BCA Table
W 'function rBca(){'
W '  const srch=document.getElementById("bSrc").value.toLowerCase();'
W '  const per=document.getElementById("bPer").value;'
W '  const typ=document.getElementById("bTyp").value;'
W '  let f=bcaD.txs.filter(t=>{'
W '    if(per&&per!=="ALL"&&t.monthKey!==per)return false;'
W '    if(typ==="in"&&t.type!=="in")return false;'
W '    if(typ==="out"&&t.type!=="out")return false;'
W '    if(typ==="QRIS"&&t.category!=="QRIS")return false;'
W '    if(typ==="wallet"&&t.category!=="E-Wallet")return false;'
W '    if(typ==="risk"&&!t.riskFlagged)return false;'
W '    if(srch&&!`${t.description} ${t.party} ${t.amount} ${t.displayDate}`.toLowerCase().includes(srch))return false;'
W '    return true;'
W '  });'
W '  f.sort((a,b)=>{let va=a[bSCol],vb=b[bSCol];if(typeof va==="string")va=va.toLowerCase();if(typeof vb==="string")vb=vb.toLowerCase();return bSAsc?(va<vb?-1:va>vb?1:0):(va<vb?1:va>vb?-1:0)});'
W '  const total=f.length;const pages=Math.ceil(total/PS)||1;if(bPg>pages)bPg=pages;if(bPg<1)bPg=1;'
W '  const s=(bPg-1)*PS;const items=f.slice(s,s+PS);'
W '  document.getElementById("bTb").innerHTML=items.map(t=>`<tr onclick="oBca(''${es(t.id)}'')"><td class="mono">${t.displayDate}</td><td><span class="pill ${t.type==="in"?"c":"d"}">${t.type==="in"?"CR":"DB"}</span></td><td><span class="pill g">${t.category}</span></td><td style="font-weight:600;max-width:160px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${es(t.party)}</td><td style="color:var(--t3);max-width:250px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${es(t.description)}</td><td class="mono" style="text-align:right;font-weight:700;color:${t.type==="in"?"var(--gr)":"var(--t1)"}">${t.type==="in"?"+":"-"}${fI(t.amount)}</td></tr>`).join("");'
W '  document.getElementById("bPgi").textContent=`${total>0?s+1:0}-${Math.min(s+PS,total)} / ${total.toLocaleString("id-ID")}`;'
W '  document.getElementById("bPrv").disabled=bPg<=1;document.getElementById("bNxt").disabled=bPg>=pages;'
W '}'
W 'function sBca(c){if(bSCol===c)bSAsc=!bSAsc;else{bSCol=c;bSAsc=true;}rBca()}'
W 'function pBca(d){bPg+=d;rBca()}'

# 1xBet Table
W 'function rXbt(){'
W '  if(!window.XBET_DATA)return;'
W '  const srch=document.getElementById("xSrc").value.toLowerCase();'
W '  const typ=document.getElementById("xTyp").value;'
W '  const yr=document.getElementById("xYr").value;'
W '  let f=window.XBET_DATA.filter(x=>{if(typ!=="ALL"&&x.type!==typ)return false;if(yr!=="ALL"&&String(x.year)!==yr)return false;if(srch&&!`${x.date} ${x.amount} ${x.channel} ${x.status} ${x.rawText}`.toLowerCase().includes(srch))return false;return true});'
W '  f.sort((a,b)=>{let va=a[xSCol],vb=b[xSCol];if(typeof va==="string")va=va.toLowerCase();if(typeof vb==="string")vb=vb.toLowerCase();return xSAsc?(va<vb?-1:va>vb?1:0):(va<vb?1:va>vb?-1:0)});'
W '  const total=f.length;const pages=Math.ceil(total/PS)||1;if(xPg>pages)xPg=pages;if(xPg<1)xPg=1;'
W '  const s=(xPg-1)*PS;const items=f.slice(s,s+PS);'
W '  document.getElementById("xTb").innerHTML=items.map(x=>`<tr onclick="oXbt(${x.id})"><td class="mono" style="color:var(--t4)">#${x.id}</td><td class="mono">${x.date}</td><td><span class="pill ${x.type==="DEPOSIT"?"d":x.type==="WITHDRAW"?"c":"g"}">${x.category}</span></td><td class="mono" style="text-align:right;font-weight:700;color:${x.type==="DEPOSIT"?"var(--rd)":x.type==="WITHDRAW"?"var(--gr)":"var(--t1)"}">${fI(x.amount)}</td><td>${x.channel}</td><td><span class="pill g">${x.status}</span></td><td style="color:var(--t3);max-width:210px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${es(x.rawText)}</td></tr>`).join("");'
W '  document.getElementById("xPgi").textContent=`${total>0?s+1:0}-${Math.min(s+PS,total)} / ${total.toLocaleString("id-ID")}`;'
W '  document.getElementById("xPrv").disabled=xPg<=1;document.getElementById("xNxt").disabled=xPg>=pages;'
W '}'
W 'function sXbt(c){if(xSCol===c)xSAsc=!xSAsc;else{xSCol=c;xSAsc=true;}rXbt()}'
W 'function pXbt(d){xPg+=d;rXbt()}'

# Ledger
W 'function rLed(){'
W '  const srch=document.getElementById("lSrc").value.toLowerCase();'
W '  const sou=document.getElementById("lSou").value;'
W '  const yr=document.getElementById("lYr").value;'
W '  const typ=document.getElementById("lTyp").value;'
W '  let f=mRows.filter(m=>{if(sou!=="ALL"&&m.source!==sou)return false;if(yr!=="ALL"&&String(m.year)!==yr)return false;if(typ!=="ALL"&&m.type!==typ)return false;if(srch&&!`${m.description} ${m.party} ${m.category} ${m.amount} ${m.displayDate}`.toLowerCase().includes(srch))return false;return true});'
W '  f.sort((a,b)=>{let va=a[lSCol],vb=b[lSCol];if(typeof va==="string")va=va.toLowerCase();if(typeof vb==="string")vb=vb.toLowerCase();return lSAsc?(va<vb?-1:va>vb?1:0):(va<vb?1:va>vb?-1:0)});'
W '  const total=f.length;const pages=Math.ceil(total/PS)||1;if(lPg>pages)lPg=pages;if(lPg<1)lPg=1;'
W '  const s=(lPg-1)*PS;const items=f.slice(s,s+PS);'
W '  document.getElementById("lTb").innerHTML=items.map(m=>`<tr onclick="oMod(''${es(m.id)}'')"><td class="mono">${m.displayDate}</td><td><span class="pill ${m.source==="BCA"?"i":m.source==="1XBET"?"g":m.source==="PINJOL"?"w":"p"}">${m.source}</span></td><td><span class="pill ${m.type==="in"?"c":"d"}">${es(m.category)}</span></td><td style="font-weight:600;max-width:170px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${es(m.party)}</td><td style="color:var(--t3);max-width:250px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${es(m.description)}</td><td class="mono" style="text-align:right;font-weight:700;color:${m.type==="in"?"var(--gr)":"var(--t1)"}">${m.type==="in"?"+":"-"}${fI(m.amount)}</td></tr>`).join("");'
W '  document.getElementById("lPgi").textContent=`${total>0?s+1:0}-${Math.min(s+PS,total)} / ${total.toLocaleString("id-ID")}`;'
W '  document.getElementById("lPrv").disabled=lPg<=1;document.getElementById("lNxt").disabled=lPg>=pages;'
W '}'
W 'function sLed(c){if(lSCol===c)lSAsc=!lSAsc;else{lSCol=c;lSAsc=true;}rLed()}'
W 'function pLed(d){lPg+=d;rLed()}'

# Annual Matrix
W 'function rAn(){'
W '  let h="";'
W '  [2023,2024,2025,2026].forEach(yr=>{'
W '    const bY=bcaD.txs.filter(t=>t.year===yr);'
W '    const bi=bY.filter(t=>t.type==="in").reduce((s,t)=>s+t.amount,0);'
W '    const bo=bY.filter(t=>t.type==="out").reduce((s,t)=>s+t.amount,0);'
W '    const xY=(window.XBET_DATA||[]).filter(x=>x.year===yr);'
W '    const dp=xY.filter(x=>x.type==="DEPOSIT").reduce((s,x)=>s+x.amount,0);'
W '    const wd=xY.filter(x=>x.type==="WITHDRAW").reduce((s,x)=>s+x.amount,0);'
W '    const net=wd-dp;const mc=new Set(bY.map(t=>t.monthKey)).size;'
W '    h+=`<tr><td style="font-weight:700">${yr}</td><td>${mc} Bln</td><td class="mono" style="color:var(--gr);font-weight:600">${fI(bi)}</td><td class="mono" style="color:var(--rd);font-weight:600">${fI(bo)}</td><td class="mono" style="color:var(--rd);font-weight:600">${fI(dp)}</td><td class="mono" style="color:var(--gr);font-weight:600">${fI(wd)}</td><td class="mono" style="font-weight:700;color:${net<0?"var(--rd)":"var(--gr)"}">${net<=0?"":"+"}${fI(net)}</td></tr>`;'
W '  });'
W '  document.getElementById("anTb").innerHTML=h;'
W '}'

# Modals
W 'function oMod(id){const m=mRows.find(x=>x.id===id);if(!m)return;opMod(`[${m.source}] Detail`,m.displayDate,m.amount,m.type==="in",`${m.source} - ${m.category}`,m.party,"Normal",m.description)}'
W 'function oBca(id){const t=bcaD.txs.find(x=>x.id===id);if(!t)return;opMod("Mutasi BCA",t.displayDate,t.amount,t.type==="in",`BCA - ${t.category}`,t.party,t.riskFlagged?"QRIS Suspect":"Normal",t.description)}'
W 'function oXbt(id){const x=(window.XBET_DATA||[]).find(t=>t.id===id);if(!x)return;opMod(`1xBet #${x.id}`,x.date,x.amount,x.type==="WITHDRAW",`1xBet - ${x.category}`,`1xBet (${x.channel})`,x.status,x.rawText)}'
W 'function opMod(ttl,dt,amt,isIn,cat,pty,sts,dsc){'
W '  document.getElementById("mTtl").textContent=ttl;'
W '  document.getElementById("mDt").textContent=dt;'
W '  document.getElementById("mAmt").textContent=(isIn?"+":"-")+fI(amt);'
W '  document.getElementById("mAmt").className="mrv b "+(isIn?"g":"r");'
W '  document.getElementById("mCat").textContent=cat;'
W '  document.getElementById("mStt").innerHTML=`<span class="pill ${sts==="Normal"?"c":"w"}">${sts}</span>`;'
W '  document.getElementById("mPty").textContent=pty;'
W '  document.getElementById("mDsc").textContent=dsc;'
W '  document.getElementById("mbo").classList.add("op");'
W '}'
W 'function cMod(){document.getElementById("mbo").classList.remove("op")}'

# PDF Upload
W 'async function upPdf(e){'
W '  const files=Array.from(e.target.files);'
W '  for(const f of files){'
W '    const buf=await f.arrayBuffer();'
W '    const r=await pdfBytes(new Uint8Array(buf),f.name);'
W '    bcaD.stmts.push({file:f.name,monthKey:r.meta.monthKey,periodLabel:r.meta.periodLabel,sum:r.summary,txc:r.txs.length});'
W '    bcaD.txs=bcaD.txs.concat(r.txs);'
W '    r.txs.forEach(t=>mRows.push({...t}));'
W '  }'
W '  bcaD.txs.sort((a,b)=>a.date.localeCompare(b.date));mRows.sort((a,b)=>a.date.localeCompare(b.date));'
W '  rBca();alert(`${files.length} PDF berhasil ditambahkan.`);'
W '}'

# CSV Export
W 'function expCsv(){'
W '  let rows=[],fn="audit.csv";'
W '  if(actTab==="bca"){fn="mutasi_bca.csv";rows.push(["ID","Tanggal","Tipe","Kategori","Pihak","Keterangan","Nominal"]);bcaD.txs.forEach(t=>rows.push([t.id,t.date,t.type,t.category,`"${t.party.replace(/"/g,''""'')}"`,`"${t.description.replace(/"/g,''""'')}"`,t.amount]))}'
W '  else if(actTab==="jd"){fn="judi_1xbet.csv";rows.push(["ID","Waktu","Tipe","Kategori","Nominal","Kanal","Status","Keterangan"]);(window.XBET_DATA||[]).forEach(x=>rows.push([x.id,x.date,x.type,x.category,x.amount,x.channel,x.status,`"${x.rawText.replace(/"/g,''""'')}"`]))}'
W '  else{fn="buku_besar.csv";rows.push(["ID","Sumber","Tanggal","Tipe","Kategori","Pihak","Keterangan","Nominal"]);mRows.forEach(m=>rows.push([m.id,m.source,m.date,m.type,m.category,`"${m.party.replace(/"/g,''""'')}"`,`"${m.description.replace(/"/g,''""'')}"`,m.amount]))}'
W '  const u="data:text/csv;charset=utf-8,"+encodeURIComponent(rows.map(r=>r.join(",")).join("\n"));'
W '  const a=document.createElement("a");a.href=u;a.download=fn;document.body.appendChild(a);a.click();document.body.removeChild(a);'
W '}'

# Charts
W 'function initCharts(){'
W '  const gc=(id,type,data,opts)=>{const c=document.getElementById(id);if(c)new Chart(c,{type,data,options:{responsive:true,maintainAspectRatio:false,...opts}})};'
W '  gc("cDonut","doughnut",{labels:["Biaya Kuliah","Judi 1xBet","Pinjol Shopee"],datasets:[{data:[38800000,4760602,4766903],backgroundColor:["#6366f1","#ef4444","#f59e0b"],borderWidth:0}]},{plugins:{legend:{position:"bottom",labels:{boxWidth:10,font:{family:"Inter",size:11}}},tooltip:{callbacks:{label:i=>` ${i.label}: ${fI(i.raw)}`}}},cutout:"64%"});'
W '  gc("cCompare","bar",{labels:["Judi Hilang","SPP 1 Sem","SPP 1.25x","Total DPP","Total Kuliah"],datasets:[{data:[4760602,3800000,4750000,9750000,38800000],backgroundColor:["#ef4444","#3b82f6","#ef4444","#6366f1","#10b981"],borderRadius:5}]},{plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{grid:{color:"rgba(128,128,128,0.07)"},ticks:{callback:v=>"Rp "+(v/1000000)+"Jt"}}}});'
W '  if(bcaD.stmts.length)gc("cBcaTL","bar",{labels:bcaD.stmts.map(s=>s.periodLabel),datasets:[{label:"CR",data:bcaD.stmts.map(s=>s.sum?.totalIn||0),backgroundColor:"#10b981",borderRadius:2},{label:"DB",data:bcaD.stmts.map(s=>s.sum?.totalOut||0),backgroundColor:"#ef4444",borderRadius:2}]},{plugins:{legend:{position:"top"}},scales:{x:{grid:{display:false},ticks:{maxRotation:45,minRotation:45,font:{size:10}}},y:{grid:{color:"rgba(128,128,128,0.07)"},ticks:{callback:v=>"Rp "+(v/1000000)+"Jt"}}}});'
W '  if(window.XBET_DATA){'
W '    const s=[...window.XBET_DATA].sort((a,b)=>a.id-b.id);const st=Math.ceil(s.length/50);const sm=s.filter((_,i)=>i%st===0||i===s.length-1);'
W '    gc("cCumL","line",{labels:sm.map(x=>x.isoDate),datasets:[{data:sm.map(x=>x.cumNet),borderColor:"#ef4444",backgroundColor:"rgba(239,68,68,0.06)",fill:true,borderWidth:2,pointRadius:0,tension:0.4}]},{plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{maxTicksLimit:6,font:{size:10}}},y:{grid:{color:"rgba(128,128,128,0.07)"},ticks:{callback:v=>fI(v)}}}});'
W '    const hr=Array(24).fill(0);window.XBET_DATA.filter(x=>x.type==="DEPOSIT").forEach(x=>{hr[x.hour]=(hr[x.hour]||0)+1});'
W '    gc("cHour","bar",{labels:Array.from({length:24},(_,i)=>String(i).padStart(2,"0")+":00"),datasets:[{data:hr,backgroundColor:Array.from({length:24},(_,i)=>i<=5?"#ef4444":"#3b82f6"),borderRadius:3}]},{plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{font:{size:9}}},y:{grid:{color:"rgba(128,128,128,0.07)"}}}});'
W '    const ew=window.XBET_DATA.filter(x=>x.channel.toLowerCase().includes("wallet")).reduce((s,x)=>s+x.amount,0);'
W '    const bk=window.XBET_DATA.filter(x=>x.channel.toLowerCase().includes("bank")).reduce((s,x)=>s+x.amount,0);'
W '    gc("cChan","doughnut",{labels:["E-Wallet","Bank Transfer"],datasets:[{data:[ew,bk],backgroundColor:["#6366f1","#3b82f6"],borderWidth:0}]},{plugins:{legend:{position:"bottom"},tooltip:{callbacks:{label:i=>` ${i.label}: ${fI(i.raw)}`}}},cutout:"60%"});'
W '    const dw={Monday:0,Tuesday:0,Wednesday:0,Thursday:0,Friday:0,Saturday:0,Sunday:0};'
W '    window.XBET_DATA.filter(x=>x.type==="DEPOSIT").forEach(x=>{if(dw[x.dayOfWeek]!==undefined)dw[x.dayOfWeek]++});'
W '    gc("cDoW","bar",{labels:["Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu"],datasets:[{data:Object.values(dw),backgroundColor:"#3b82f6",borderRadius:4}]},{plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{grid:{color:"rgba(128,128,128,0.07)"}}}});'
W '  }'
W '  gc("cPjPie","doughnut",{labels:["SPinjam (5x)","SPayLater"],datasets:[{data:[4270259,496647],backgroundColor:["#f59e0b","#ef4444"],borderWidth:0}]},{plugins:{legend:{position:"bottom"},tooltip:{callbacks:{label:i=>` ${i.label}: ${fI(i.raw)}`}}},cutout:"60%"});'
W '  gc("cPjTl","bar",{labels:["09 Nov","10 Nov","11 Nov Pg","11 Nov Sg","14 Nov","22 Nov","Jan 2025"],datasets:[{label:"Pinjaman",data:[471107,471107,461683,942206,942206,981947,496647],backgroundColor:["#f59e0b","#f59e0b","#ef4444","#ef4444","#ef4444","#ef4444","#6366f1"],borderRadius:4}]},{plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{grid:{color:"rgba(128,128,128,0.07)"},ticks:{callback:v=>fI(v)}}}});'
W '  gc("cKlPie","doughnut",{labels:["SPP","DPP","Tambahan"],datasets:[{data:[26600000,9750000,2450000],backgroundColor:["#6366f1","#3b82f6","#10b981"],borderWidth:0}]},{plugins:{legend:{position:"bottom"},tooltip:{callbacks:{label:i=>` ${i.label}: ${fI(i.raw)}`}}},cutout:"60%"});'
W '  gc("cKlBar","bar",{labels:["Sem 1","Sem 2","Sem 3","Sem 4","Sem 5","Sem 6","Sem 7"],datasets:[{data:[10250000,5800000,5300000,5300000,3800000,3800000,4550000],backgroundColor:"#6366f1",borderRadius:5}]},{plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{grid:{color:"rgba(128,128,128,0.07)"},ticks:{callback:v=>"Rp "+(v/1000000)+"Jt"}}}});'
W '}'

W 'window.addEventListener("DOMContentLoaded",init);'
W '</script>'
W '</body></html>'

$indexPath = Join-Path $PSScriptRoot "..\index.html"
$out | Set-Content -Path $indexPath -Encoding UTF8
Write-Host "index.html generated: $((Get-Item $indexPath).Length) bytes"
